### ISSUE TITLE
Autoupdate seemingly not working

### ISSUE THREAD

**Issue by kevinaquick** [paritytech/parity-ethereum#9396]
Parity 1.11.7
Linux  Ubuntu 16.04.5 
Running as a POA Private Network (but have also tested on a node connected to the live public Ethereum chain)
Parity has been restarted

From the documentation I understand that Parity should autoupdate to the latest version, however we have not observed this happening at all on our nodes (20 or so). Reading further we have added the following to the nodes configuration file:

auto_update = "all"
release_track = "stable"

I read that the update feature uses a special contract and that updates are triggered after a number of blocks have been validated, so our nodes we have made sure lots of blocks have been validated and still Parity remained on 1.11.7 (even though 1.11.8 stable was available). This was true for both our private POA networks and the node we have connected to main live ethereum chain (where of course there is a constant stream of new blocks being mined).

Are we missing something we need to do to enable the autoupdate - do we have to specify where the autoupdate contract is etc.

For the moment we have manually updated our nodes but really wish to be able them to update themselves

Many thanks for any help you can give

**Comment by Tbaut** [comment]
If you are running a private PoA and haven't deployed the contract, then the auto-update will not work.
On Mainnet or Kovan, you need to make sure you have the ancient-blocks downloaded (if you did a warp-sync) as the auto-update will not trigger for security reasons.

If you are sure about what I wrote above, then could you please provide the logs with `-l updater`?

**Comment by kevinaquick** [comment]
OK many thanks for the reply

On the mainnet we probably did do a warp-sync so we can certainly change that setting and resync and give that ago. 

With respect to our private PoA - how do we deploy the contract? obviously we can compile and and get abi and binary of the contract I saw pointed to in the documentation and publish to the blockchain etc but how do you specify to use the contract  is this something that has to be defined in the genesis data etc and maybe included like a validator contract?

**Comment by Tbaut** [comment]
You need to deploy the [name registry contract](https://github.com/parity-contracts/name-registry) (more info [here](https://wiki.parity.io/Parity-name-registry.html)) first and then deploy and register the updater contract also called `operations` contract under the name "operations".
The registrar is the contract that needs to be specified in the [genesis file](https://wiki.parity.io/Chain-specification).

The client will look for the `operations` contract address for the updates.

**Comment by kevinaquick** [comment]
Many thanks forgetting back - I have followed the link to the name registry page and the associated contracts and particularly the SImpleRegistry contract and from looking at the code from what I can see, the contract requires not only a name to register ("operations" from your message), but also a 'key' string for an inner mapping (I assume for the purpose in general that any name registered can map to multiple addresses). SO, if I register the Operation contract under the name "operations" what 'key' should I use with it (I assume the system must be using a specific value)

**Comment by Tbaut** [comment]
Sorry not to have mentioned it specifically, ([it's hidden here](https://wiki.parity.io/Parity-name-registry)) but it works a little bit like DNS, so you should use the letter `A` as the key.

**Comment by kevinaquick** [comment]
:-) I saw the 'A' in the example but didn't take as more than an example at the time. I think I can see all that I have to do now - thanks again

**Comment by kevinaquick** [comment]
@Tbaut - hope you can bear with me a little bit more - not sure I have it working correctly at the moment - I have published the SimpleRegistry.sol to the blockchain and have its address - I have published a copy of SImpleOperations.sol and have its address (both contracts as downloaded from the Parity GitHub pages.

I have then called the function in the SimpleRegistry contract to 'reserve' the name "operations" passing the sha3 value of "operations" to the function. I then have called the setAddress function passing in the parameters of the sha3 of "operations", 'A' and the operations contract address. Finally I have called the getAddress function to check what the address the contract has stored. However, the value returned from the geAddress call is not the same at all as the operations contract address is that right - I assume it should surely be the same? The values I have are:

operations contract address = 0xe8db618a60b682582a389eb31af5906da4cd5bb5
value returned by calling getAddress function in the SimpleRegistry contract = 0x0000000000000000000000000000000000000060

(I see the contract converts the address value to a bytes32 in the setAddress and then on calling the getAddress it returns the bytes32 as an address). so the Node JS functions I have used for the above:

function reserveName() {
	var aContract = web3.eth.contract(registryABI);
	var contractInstance = aContract.at(registryContractAddress);
	var name = "operations";
	var reservationCost = web3.toWei(1);

	var handler = function(e, txhash) {
		if (!e) {
			console.log("Reserve name transaction: " + txhash);
		} else {
			console.log(e);
		}
		return null;
	};	
	contractInstance.reserve(web3.sha3(name), {from: accountToUse, value: reservationCost, gasPrice: gasPrice, gas: 3000000}, handler);
}

function setAddressToReservedName() {
	var aContract = web3.eth.contract(registryABI);
	var contractInstance = aContract.at(registryContractAddress);
	var name = "operations";

	var handler = function(e, txhash) {
		if (!e) {
			console.log("setAddress transaction: " + txhash);
		} else {
			console.log(e);
		}
		return null;
	};	
	contractInstance.setAddress(web3.sha3(name), 'A', operationsContractAddress, {from: accountToUse, gasPrice: gasPrice, gas: 3000000}, handler);
}

function getAddressOfReservedName() {
	var aContract = web3.eth.contract(registryABI);
	var contractInstance = aContract.at(registryContractAddress);
	var name = "operations";

	var handler = function(e, address) {
		if (!e) {
			console.log("address: " + address);
		} else {
			console.log(e);
		}
		return null;
	};	
	contractInstance.getAddress(web3.sha3(name), 'A', handler);
}

**Comment by Tbaut** [comment]
You've got to double check your code, I deployed manually [SimpleRegistry.sol](https://github.com/parity-contracts/name-registry/blob/master/contracts/SimpleRegistry.sol) with [Remix](https://remix.ethereum.org) on a dev chain and it worked as expected. A couple thing to double check:

- Do you send enough fee for the reservation (default 1000000000000000000) and does the Tx get properly mined (e.g. no error)?
- Even though this shouldn't be a problem for you right now, Sha3 and Keccak function aren't 100% the same, although web3.sha3 should match with keccak. Just to make sure, parity has a hash tool:
```
$ parity tools hash <(echo -n "operations")
51ca38ad0d9c8193e2a97a5c1967a34e79112bdff5a5783aad187224fb70165e
```

**Comment by kevinaquick** [comment]
@Tbaut thanks for testing - it took a while for me to get there, but eventually twigged that when doing calls like the contractInstance.getAddress(web3.sha3(name), 'A', handler); from node js you have to prebend "0x" to the front to get it to convert properly to a bytes32 i.e. contractInstance.getAddress('0x'+web3.sha3(name), 'A', handler); Now it behaves! just now see if the autoupdate is triggered.

**Comment by Tbaut** [comment]
I'm glad you could figure it out!

**Comment by kevinaquick** [comment]
@Tbaut Sorry to keep posting but I am still having problems with getting the autoupdater working on our private PoA network.

So to recap - I have:

- published a copy of simple registry contract (SimpleRegistry.sol) onto the blockchain. 
- compiled and published a copy of SimpleOperations.sol
- I have registered the name "operations" on the registry contract and the added the operations contract address to the registry contract under the name "operations" and key "A" - and have checked the value is stored in the contract querying the getAddress contract function.
- I have edited our spec.json file to include the options parameter "registrar" with the address of the  registry contract i.e.

.
.
.
    "params": {
        "gasLimitBoundDivisor": "0x400",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "emptyStepsTransition" : "0",
        "networkID" : "0x4BF",
        "eip140Transition": "0x15",
        "eip211Transition": "0x15",
        "eip214Transition": "0x15",
        "eip658Transition": "0x15",
        "registrar": "0xe45897bb85f6f8391fffd003fed2be62b9128cca"
    },
.
.
.

- I have edited our configuration file to check for all stable release i.e  in the following snippet of the configuration file

[parity]
chain = "/data/parity/spec.json"
base_path = "/data/parity"
db_path = "/data/parity/nodedata"
keys_path = "/data/parity/keys"
identity = "OUKMi IoC 01"
auto_update = "all"
release_track = "stable"

I have restarted Parity with the following command:

parity --config /data/parity/node.toml --auto-update-delay=2 --auto-update-check-frequency=5

so  as I understand it, an update will be checked after a maximum of 7 blocks are published (I also have the other nodes configured with just the default values for frequency of checking). Sufficient blocks have subsequently been published to the chain (well over 100) such that all of the nodes should by now have triggered an update, but they haven't (they are variously on 1.11.7 and 1.11.8 and according to the github page there are a couple of stable releases after the version we have installed)

Am I missing something that needs to be set for the updates to happen?

**Comment by Tbaut** [comment]
This looks good from your description, could you post the logs printed with the addition of `-l updater`?

**Comment by jbentke** [comment]
I am now at the same point, I guess we need to register a new release for our private network in the operations contract?

**Comment by Tbaut** [comment]
Just to make sure this is clear, you are now the owner and admin of the operations contract, this also means that you will need to `addRelease`, `addChecksum` and generally manage the new releases. There is no documentation on that though :(

**Comment by kevinaquick** [comment]
OK - so you are saying on a private PoA its not an entirely automatic updater, but rather in such a case its a centrally managed updater (and explain why nothing has happened re updating the servers!) - does it know where the updater install files reside or is a download address part of the release parameters in the contract (obviously I need to have a good study  of the operations contract...)

**Comment by Tbaut** [comment]
>so you are saying on a private PoA its not an entirely automatic updater

Absolutely, it's automatic for anybody but the one/ones in charge of letting the contract know when there is a new version :)

**Comment by kevinaquick** [comment]
So really without any documentation regarding what the various parameters in addRelease, addChecksum have to be set to/generated, there is probably little chance we will be able to implement this as a centrally managed update system - there is still also the question as to where the updater installer files reside - is it the Parity GitHub repository or do we have to keep our own copies on our network somewhere where all the nodes can access it and is that specified in the contract (although not sure I could see that) etc etc

**Comment by jbentke** [comment]
Yeah, the biggest question for us is where the actual update is coming from. If it is hardcoded in the actual rust code then we would have to run a modified Parity version from the beginning since we would not be able to fork to a different release that is not published by parity.

**Comment by Tbaut** [comment]
The url is resolved from the checksum. I was made aware of this page explaining step by step how to deploy the contract with Parity UI (outdated). However, this is well detailed: https://github.com/paritytech/push-release

**Comment by natlg** [comment]
We've deployed auto-updater server and contracts for the POA Network, though it's still under testing. May be these instructions can be helpful for you too: https://github.com/poanetwork/auto-updater-setup

**Comment by jbentke** [comment]
༼ つ ◕_◕ ༽つ Thank you!!!
